# Generated by Django 2.0.2 on 2018-02-27 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20180227_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='founded_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date founded'),
            preserve_default=False,
        ),
    ]
