# Generated by Django 2.0.2 on 2018-03-07 14:54

from django.db import migrations
from django.utils.text import slugify
from django.db import models

class Migration(migrations.Migration):
    SLUG_LENGTH = 63
    dependencies = [
        ('organizer', '0004_auto_20180227_1616'),
    ]

    def add_slug_data(apps, schema_editor):
        NewsLink = apps.get_model('organizer', 'NewsLink')
        query = NewsLink.objects.all()
        for newslink in query:
            expected_slug = slugify(newslink.title)
            rivals = (
                NewsLink.objects.filter(startup=newslink.startup,
                                       slug__startswith=expected-slug).count()
            )
            if rivals > 0:
                str_len = (SLUG_LENGTH - len(str(rivals)))
                newslink.slug = "{}-{}".format(expected_slug[:str_len-1], rivals + 1)
            else:
                newslink_slug = expected_slug
            newslink.save()
        
    def remove_slug_data(apps, schema_editor):
        NewsLink = apps.get_model('organizer', 'NewsLink')
        NewsLink.objects.update(slug='')
    
    operations = [
        migrations.AddField(
            model_name='newslink',
            name='slug',
            field=models.SlugField(max_length=SLUG_LENGTH, default=''),
        ),
        migrations.RunPython(
            add_slug_data,
            reverse_code=remove_slug_data
        ),
        migrations.AlterField(
            model_name='newslink',
            name='slug',
            field=models.SlugField(
                max_length=SLUG_LENGTH
            ),
        ),
    ]
    
   
            

    